services:
  postgres:
    image: postgres:16
    container_name: food_delivery_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - food_delivery_data:/var/lib/postgresql/data

volumes:
  food_delivery_data:
